# docker-compose.yml
version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - prisma_data:/app/prisma
    environment:
      - DATABASE_URL=file:./prisma/dev.db

volumes:
  prisma_data: